### ISSUE TITLE
热更新关于图片的问题

### ISSUE THREAD

**Issue by zk6859** [reactnativecn/react-native-pushy#105]
我尝试在项目中加入了图片，结果上传版本的时候报错了。那么，更新版本的时候不能加入静态资源吗？如果要加入，必须得发布新的包吗？

**Comment by zk6859** [comment]
错误如下
Bundling with React Native version:  0.44.0
Loading dependency graph, done.
TypeError: Corrupt JPG, exceeded buffer limits
    at validateBuffer (E:\project\test\node_modules\image-size\lib\types\jpg.js:58:11)
    at Object.calculate (E:\project\test\node_modules\image-size\lib\types\jpg.js:77:5)
    at lookup (E:\project\test\node_modules\image-size\lib\index.js:27:31)
    at E:\project\test\node_modules\image-size\lib\index.js:93:22
    at E:\project\test\node_modules\image-size\lib\index.js:50:9
    at E:\project\test\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by sunnylqm** [comment]
图片太大了吧
