### ISSUE TITLE
执行pushy bundle --platform android 错误

### ISSUE THREAD

**Issue by wuyunqiang** [reactnativecn/react-native-pushy#112]
"react": "^16.0.0-alpha.12",
	"react-native": "^0.45.1",
	"react-native-update": "^4.0.5"

Cannot find module '/Users/xxx/Documents/test/testphone/node_modules/react-native/local-cli/core/default.config'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/wuyunqiang/Documents/test/testphone/node_modules/react-native-update/local-cli/lib/bundle.js:447:91)
    at Generator.next (<anonymous>)
    at step (/Users/wuyunqiang/Documents/test/testphone/node_modules/react-native-update/local-cli/lib/bundle.js:42:191)
    at /Users/wuyunqiang/Documents/test/testphone/node_modules/react-native-update/local-cli/lib/bundle.js:42:368
    at <anonymous>

**Comment by sunnylqm** [comment]
0.45又有改动，请等待pushy升级兼容

**Comment by wuyunqiang** [comment]
好的 辛苦辛苦

**Comment by shangwfa** [comment]
我也遇到这个问题了，怎么破

**Comment by yuanzougaofei97** [comment]
怎么还没升级？没人维护了吗

**Comment by ftb2010** [comment]
@sunnylqm 这个0.45.1现在还是报这个错，你们还没修复好吗？有什么过渡的解决方案没有？

**Comment by sunnylqm** [comment]
已经修复了啊  你pushy什么版本@ftb2010

**Comment by ftb2010** [comment]
@sunnylqm "react": "^16.0.0-alpha.12",
"react-native": "^0.45.1",
"react-native-update": "^4.0.5"

**Comment by sunnylqm** [comment]
现在是5.x版本了

**Comment by ftb2010** [comment]
React Native版本 | react-native-update版本
-- | --
0.26及以下 | 1.0.x
0.27 - 0.28 | 2.x
0.29 - 0.33 | 3.x
0.34 - 0.45 | 4.x
0.46及以上 | 5.x

**Comment by ftb2010** [comment]
0.45不是仅支持4.x吗？

**Comment by sunnylqm** [comment]
我估计0.45没有修复，你可能需要升级rn

**Comment by ftb2010** [comment]
好吧，我以为你们把pushy升级兼容0.45.1 @sunnylqm
