### ISSUE TITLE
android 热更新引用静态图片(require 方式访问rn项目下图片)闪退

### ISSUE THREAD

**Issue by wuyunqiang** [reactnativecn/react-native-pushy#114]
10905-10934/com.pepperoniapptemplate E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                                          Process: com.pepperoniapptemplate, PID: 10905
                                                                          java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                              at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                           Caused by: java.lang.IllegalStateException: closed
                                                                              at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:164)
                                                                              at com.facebook.react.devsupport.JSPackagerWebSocketClient.closeWebSocketQuietly(JSPackagerWebSocketClient.java:103)
                                                                              at com.facebook.react.devsupport.JSPackagerWebSocketClient.closeQuietly(JSPackagerWebSocketClient.java:97)
                                                                              at com.facebook.react.devsupport.DevServerHelper$2.doInBackground(DevServerHelper.java:151)
                                                                              at com.facebook.react.devsupport.DevServerHelper$2.doInBackground(DevServerHelper.java:147)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by tdzl2003** [comment]
看起来这是debug模式下网络抖动导致的RN本身的崩溃，和热更新没有什么关系。
热更新应该在release模式下测试。
