### ISSUE TITLE
 pushy bundle --platform ios

### ISSUE THREAD

**Issue by leeshuangai** [reactnativecn/react-native-pushy#125]
when run ' pushy bundle --platform ios' ,

Error: Cannot find module '/Applications/Git/code/ios/RNComponent/node_modules/react-native/packager/babelRegisterOnly'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/Git/code/ios/RNComponent/node_modules/react-native-update/local-cli/lib/bundle.js:436:7)
    at Generator.next (<anonymous>)
    at step (/Applications/Git/code/ios/RNComponent/node_modules/react-native-update/local-cli/lib/bundle.js:42:191)
    at /Applications/Git/code/ios/RNComponent/node_modules/react-native-update/local-cli/lib/bundle.js:42:368

**Comment by temple002** [comment]
在最新的版本中，路径又改了，把\node_modules\react-native-update\local-cli\lib\bundle.js中439行的'metro-bundler/src/babelRegisterOnly'改为'require('metro/src/babelRegisterOnly');'

**Comment by sunnylqm** [comment]
Fixed in https://github.com/reactnativecn/react-native-pushy/pull/205
