### ISSUE TITLE
Invariant Violation: Can't find "rn-cli.config.js" file

### ISSUE THREAD

**Issue by Albertao** [reactnativecn/react-native-pushy#133]
`react-native-update-cli: 0.1.0
react-native-update: 4.0.6
react-native: 0.47.1`

pushy bundle --platform android时发生错误，信息如下：

`Bundling with React Native version:  0.47.1
Invariant Violation: Can't find "rn-cli.config.js" file in any parent folder of "C:\Projects\Android\AllVoices"
    at invariant (C:\Projects\Android\AllVoices\node_modules\react-native\node_modules\fbjs\lib\invariant.js:44:15)
    at Object.findWithPathCustom (C:/Projects/Android/AllVoices/node_modules/react-native/local-cli/util/Config.js:209:5)
    at Object.findCustom (C:/Projects/Android/AllVoices/node_modules/react-native/local-cli/util/Config.js:200:19)
    at Object.find (C:/Projects/Android/AllVoices/node_modules/react-native/local-cli/util/Config.js:191:19)
    at Object.<anonymous> (C:\Projects\Android\AllVoices\node_modules\react-native-update\local-cli\lib\bundle.js:451:34)
    at Generator.next (<anonymous>)
    at step (C:\Projects\Android\AllVoices\node_modules\react-native-update\local-cli\lib\bundle.js:310:191)
    at C:\Projects\Android\AllVoices\node_modules\react-native-update\local-cli\lib\bundle.js:310:361
    at <anonymous>`

**Comment by zanblo** [comment]
我新建了一个空文件，编译过去了

**Comment by Albertao** [comment]
解决了，在项目根目录新建一个“rn-cli.config.js”的文件即可
