### ISSUE TITLE
Can't find "rn-cli.config.js" file in any parent folder of "C:\rn\aaa\RnDemo"

### ISSUE THREAD

**Issue by lk2017** [reactnativecn/react-native-pushy#136]
执行命令; pushy bundle --platform android 时报错，求大神帮忙解答。

Invariant Violation: Can't find "rn-cli.config.js" file in any parent folder of "C:\rn\aaa\RnDemo"
    at invariant (C:\rn\aaa\RnDemo\node_modules\react-native\node_modules\fbjs\lib\invariant.js:44:15)
    at Object.findWithPathCustom (C:/rn/aaa/RnDemo/node_modules/react-native/local-cli/util/Config.js:216:5)
    at Object.findCustom (C:/rn/aaa/RnDemo/node_modules/react-native/local-cli/util/Config.js:207:19)
    at Object.find (C:/rn/aaa/RnDemo/node_modules/react-native/local-cli/util/Config.js:198:19)
    at Object.<anonymous> (C:\rn\aaa\RnDemo\node_modules\react-native-update\local-cli\lib\bundle.js:451:34)
    at next (native)
    at step (C:\rn\aaa\RnDemo\node_modules\react-native-update\local-cli\lib\bundle.js:310:191)
    at C:\rn\aaa\RnDemo\node_modules\react-native-update\local-cli\lib\bundle.js:310:361

自己尝试了将node_modules/metro-bundler/src目录下的rn-cli.config.js文件引入根目录，修改了引用路径，而引发了更多的问题。求大神指导怎么解决上述问题，小白初学react-native，很多方面不太懂。

**Comment by sunnylqm** [comment]
应该是在项目目录里建一个空的rn-cli.config.js即可

**Comment by lk2017** [comment]
@sunnylqm 感谢你的帮助，按照你的做法就行得通了。

**Comment by sunnylqm** [comment]
已在5.x版本中修复
