### ISSUE TITLE
pushy bundle --platform android 报错　　at DependencyGraph._getAbsolutePath

### ISSUE THREAD

**Issue by yoonzm** [reactnativecn/react-native-pushy#160]
"react": "16.0.0",
    "react-native": "0.48.0",
    "react-native-update": "^5.0.0"

Platform(ios/android): android
Bundling with React Native version:  0.48.0
Scanning 647 folders for symlinks in /home/yoon/workspace/test-pro/hot_push/node_modules (13ms)
Loading dependency graph, done.
Error
    at DependencyGraph._getAbsolutePath ('项目目录'/node_modules/metro-bundler/src/node-haste/DependencyGraph.js:304:11)
    at DependencyGraph.getDependencies ('项目目录'//node_modules/metro-bundler/src/node-haste/DependencyGraph.js:284:4136)
    at Resolver.getDependencies ('项目目录'/node_modules/metro-bundler/src/Resolver/index.js:122:27)
    at'项目目录'/node_modules/metro-bundler/src/Bundler/index.js:638:39
    at Generator.next (<anonymous>)
    at step ('项目目录'/node_modules/metro-bundler/src/Bundler/index.js:13:1336)
    at '项目目录'/node_modules/metro-bundler/src/Bundler/index.js:13:1496
    at <anonymous>

**Comment by yoonzm** [comment]
自问自答 rn版本改为0.49.5即可

**Comment by yoonzm** [comment]
不改版本的情况下增加 index.ios/android.js　文件即可
