### ISSUE TITLE
pushy uploadApk 上传apk报错 Index out of range

### ISSUE THREAD

**Issue by Davia2017** [reactnativecn/react-native-pushy#161]
PS E:\work\study\HotUpdate> pushy uploadApk android/app/build/outputs/apk/app-release.apk
RangeError: Index out of range
    at checkOffset (buffer.js:972:11)
    at Buffer.readUInt16LE (buffer.js:1018:5)
    at BinaryXmlParser.readU16 (E:\work\study\HotUpdate\node_modules\node-apk-parser\lib\apkreader\parser\binaryxml.js:98:25)
    at BinaryXmlParser.readString (E:\work\study\HotUpdate\node_modules\node-apk-parser\lib\apkreader\parser\binaryxml.js:293:16)
    at BinaryXmlParser.readStringPool (E:\work\study\HotUpdate\node_modules\node-apk-parser\lib\apkreader\parser\binaryxml.js:332:32)
    at BinaryXmlParser.parse (E:\work\study\HotUpdate\node_modules\node-apk-parser\lib\apkreader\parser\binaryxml.js:467:12)
    at ManifestParser.parse (E:\work\study\HotUpdate\node_modules\node-apk-parser\lib\apkreader\parser\manifest.js:143:33)
    at ApkReader.readManifestSync (E:\work\study\HotUpdate\node_modules\node-apk-parser\lib\apkreader.js:37:55)
    at getApkVersion (E:\work\study\HotUpdate\node_modules\react-native-update\local-cli\lib\utils.js:82:27)
    at Object.<anonymous> (E:\work\study\HotUpdate\node_modules\react-native-update\local-cli\lib\package.js:110:51)

**Comment by lailibo8** [comment]
@Davia2017 解决了吗我也出现了这个问题

**Comment by wanyao1990** [comment]
@Davia2017 同上，也是遇到这个问题

**Comment by feida** [comment]
同上，一样的问题 apk 根本上传不了 总报错

**Comment by budiga** [comment]
同样的问题，求解

**Comment by zjuawen** [comment]
node_modules\node-apk-parser\lib\apkreader\parser\binaryxml.js:293行
修改为：this.readU8();
![2018-03-06 2 52 00](https://user-images.githubusercontent.com/6418958/37018173-58b8f2d4-214e-11e8-802f-adde6a061898.png)

**Comment by budiga** [comment]
thank you!可以了！@zjuawen

**Comment by sunnylqm** [comment]
5.3.0 版本应该修复了这个问题，如还有重现请重开issue
