### ISSUE TITLE
pushy uploadApk android/app/build/outputs/apk/app-release.apk报错

### ISSUE THREAD

**Issue by 18705320883** [reactnativecn/react-native-pushy#163]
Error: Validation error
    at D:\HelloRN-master\node_modules\react-native-update\local-cli\lib\api.js:8:27
    at next (native)
    at step (D:\HelloRN-master\node_modules\react-native-update\local-cli\lib\api.js:82:
    at D:\HelloRN-master\node_modules\react-native-update\local-cli\lib\api.js:82:361
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by sunnylqm** [comment]
需要修改build.grable中的版本号后再上传

**Comment by 18705320883** [comment]
pushy bundle --platform <ios|android>配置热更新版本后，
升级后版本hash变了，但是改动没有显示出来

**Comment by 18705320883** [comment]
已解决#158

**Comment by lailibo8** [comment]
@sunnylqm 仅仅修改versionCode 和 versionName 的值就可以吧，但是我修改了之后还是上传不成功
Error: Invalid filename
    at new ApkReader (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader.js:27:17)
    at Function.ApkReader.readFile (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader.js:16:14)
    at getApkVersion (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/utils.js:81:42)
    at Object.<anonymous> (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:110:51)
    at Generator.next (<anonymous>)
    at step (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:58:191)
    at /Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:58:437
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:58:99)
    at Object.uploadApk (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:131:20)
bogon:RNJKYJ lailibo$ pushy uploadApk /Users/lailibo/Desktop/app-release.apk 
RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1020:11)
    at Buffer.readUInt16LE (buffer.js:1068:5)
    at BinaryXmlParser.readU16 (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:98:25)
    at BinaryXmlParser.readString (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:293:16)
    at BinaryXmlParser.readStringPool (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:332:32)
    at BinaryXmlParser.parse (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:467:12)
    at ManifestParser.parse (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/manifest.js:143:33)
    at ApkReader.readManifestSync (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader.js:37:55)
    at getApkVersion (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/utils.js:82:27)
    at Object.<anonymous> (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:110:51)
bogon:RNJKYJ lailibo$ pushy uploadApk android/app/build/outputs/apk/release/app-release.apk
RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1020:11)
    at Buffer.readUInt16LE (buffer.js:1068:5)
    at BinaryXmlParser.readU16 (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:98:25)
    at BinaryXmlParser.readString (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:293:16)
    at BinaryXmlParser.readStringPool (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:332:32)
    at BinaryXmlParser.parse (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:467:12)
    at ManifestParser.parse (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/manifest.js:143:33)
    at ApkReader.readManifestSync (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader.js:37:55)
    at getApkVersion (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/utils.js:82:27)
    at Object.<anonymous> (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:110:51)
bogon:RNJKYJ lailibo$ 
如何才能解决？？？

**Comment by coldsmalltwo** [comment]
这个错误能不能改成  提示的形式  “版本号冲突，请更改您的版本号”，而不是报错

**Comment by YanmaY** [comment]
> @sunnylqm 仅仅修改versionCode 和 versionName 的值就可以吧，但是我修改了之后还是上传不成功
> Error: Invalid filename
> at new ApkReader (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader.js:27:17)
> at Function.ApkReader.readFile (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader.js:16:14)
> at getApkVersion (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/utils.js:81:42)
> at Object. (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:110:51)
> at Generator.next ()
> at step (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:58:191)
> at /Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:58:437
> at new Promise ()
> at Object. (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:58:99)
> at Object.uploadApk (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:131:20)
> bogon:RNJKYJ lailibo$ pushy uploadApk /Users/lailibo/Desktop/app-release.apk
> RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
> at checkOffset (buffer.js:1020:11)
> at Buffer.readUInt16LE (buffer.js:1068:5)
> at BinaryXmlParser.readU16 (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:98:25)
> at BinaryXmlParser.readString (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:293:16)
> at BinaryXmlParser.readStringPool (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:332:32)
> at BinaryXmlParser.parse (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:467:12)
> at ManifestParser.parse (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/manifest.js:143:33)
> at ApkReader.readManifestSync (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader.js:37:55)
> at getApkVersion (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/utils.js:82:27)
> at Object. (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:110:51)
> bogon:RNJKYJ lailibo$ pushy uploadApk android/app/build/outputs/apk/release/app-release.apk
> RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
> at checkOffset (buffer.js:1020:11)
> at Buffer.readUInt16LE (buffer.js:1068:5)
> at BinaryXmlParser.readU16 (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:98:25)
> at BinaryXmlParser.readString (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:293:16)
> at BinaryXmlParser.readStringPool (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:332:32)
> at BinaryXmlParser.parse (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:467:12)
> at ManifestParser.parse (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader/parser/manifest.js:143:33)
> at ApkReader.readManifestSync (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/node-apk-parser/lib/apkreader.js:37:55)
> at getApkVersion (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/utils.js:82:27)
> at Object. (/Users/lailibo/Documents/RNJK/RNJKYJ/node_modules/react-native-update/local-cli/lib/package.js:110:51)
> bogon:RNJKYJ lailibo$
> 如何才能解决？？？

遇到了同样的问题，初次使用，第一次上传就遇到了这个问题

**Comment by sunnylqm** [comment]
合并到 https://github.com/reactnativecn/react-native-pushy/issues/161 跟踪
