### ISSUE TITLE
pushy bundle --platform android

### ISSUE THREAD

**Issue by song6974272** [reactnativecn/react-native-pushy#178]
MacBook-Pro:FirstRN mi$ pushy bundle --platform android
Bundling with React Native version:  0.52.0
Error: Cannot find module 'metro-bundler/src/babelRegisterOnly'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/zhengnian/Desktop/FirstRN/node_modules/react-native-update/local-cli/lib/bundle.js:439:9)
    at Generator.next (<anonymous>)
    at step (/Users/zhengnian/Desktop/FirstRN/node_modules/react-native-update/local-cli/lib/bundle.js:310:191)
    at /Users/zhengnian/Desktop/FirstRN/node_modules/react-native-update/local-cli/lib/bundle.js:310:361
    at <anonymous>
MacBook-Pro:FirstRN mi$

**Comment by sunnylqm** [comment]
暂不支持0.52

**Comment by song6974272** [comment]
最高支持什么版本啊？

**Comment by sunnylqm** [comment]
目前是0.51

**Comment by basilbai** [comment]
@sunnylqm 我也遇到了同样的问题，麻烦请尽快适配下0.52版本，谢谢你！

**Comment by xiaogaofudao** [comment]
同问，什么时候适配 0.52+

**Comment by arfaWong** [comment]
@basilbai @xiaogaofudao @song6974272 
将node_modules\react-native-update\local-cli\lib\bundle.js的439行种的metro-bundler改成metro可成功运行。

**Comment by lx3133584** [comment]
@arfaWong 0.54可用, 谢谢

**Comment by chuyinweilai** [comment]
@arfaWong 0.55可用，不知道为什么改一个代码就好了，如果这么简单，为什么会不好适配呢

**Comment by arfaWong** [comment]
@chuyinweilai 具体隐患不清楚，我也是在别的论坛看到的 :)

**Comment by huangzhifei** [comment]
@chuyinweilai 没有隐患，因为在0.55.4里面metro-bundle已经改名为metro了

**Comment by zoukang1993** [comment]
> MacBook-Pro:FirstRN mi$ pushy bundle --platform android
> Bundling with React Native version: 0.52.0
> Error: Cannot find module 'metro-bundler/src/babelRegisterOnly'
> at Function.Module._resolveFilename (module.js:538:15)
> at Function.Module._load (module.js:468:25)
> at Module.require (module.js:587:17)
> at require (internal/module.js:11:18)
> at Object. (/Users/mi/Desktop/FirstRN/node_modules/react-native-update/local-cli/lib/bundle.js:439:9)
> at Generator.next ()
> at step (/Users/mi/Desktop/FirstRN/node_modules/react-native-update/local-cli/lib/bundle.js:310:191)
> at /Users/mi/Desktop/FirstRN/node_modules/react-native-update/local-cli/lib/bundle.js:310:361
> at 
> MacBook-Pro:FirstRN mi$
将node_modules\react-native-update\local-cli\lib\bundle.js
的441行种的require('metro/src/babelRegisterOnly')改成require('metro-bundler/src/babelRegisterOnly')可成功运行。

**Comment by zoukang1993** [comment]
将node_modules\react-native-update\local-cli\lib\bundle.js
的441行种的require('metro/src/babelRegisterOnly')改成require('metro-bundler/src/babelRegisterOnly')可成功运行。
