### ISSUE TITLE
热更新上传安卓版本的时候，报错误

### ISSUE THREAD

**Issue by wanyao1990** [reactnativecn/react-native-pushy#184]
RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1024:11)
    at Buffer.readUInt16LE (buffer.js:1072:5)
    at BinaryXmlParser.readU16 (/Users/wanyao/Desktop/GolfApp/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:98:25)
    at BinaryXmlParser.readString (/Users/wanyao/Desktop/GolfApp/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:293:16)
    at BinaryXmlParser.readStringPool (/Users/wanyao/Desktop/GolfApp/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:332:32)
    at BinaryXmlParser.parse (/Users/wanyao/Desktop/GolfApp/node_modules/node-apk-parser/lib/apkreader/parser/binaryxml.js:467:12)
    at ManifestParser.parse (/Users/wanyao/Desktop/GolfApp/node_modules/node-apk-parser/lib/apkreader/parser/manifest.js:143:33)
    at ApkReader.readManifestSync (/Users/wanyao/Desktop/GolfApp/node_modules/node-apk-parser/lib/apkreader.js:37:55)
    at getApkVersion (/Users/wanyao/Desktop/GolfApp/node_modules/react-native-update/local-cli/lib/utils.js:82:27)
    at Object.<anonymous> (/Users/wanyao/Desktop/GolfApp/node_modules/react-native-update/local-cli/lib/package.js:110:51)

**Comment by tdzl2003** [comment]
是否有可以引发此报错的apk可以提供给我们看一下？ 我的QQ是 402740419

**Comment by wanyao1990** [comment]
@tdzl2003 已经看到其他人解决了，在这个目录下面修改node_modules\node-apk-parser\lib\apkreader\parser\binaryxml.js:293行
修改为：this.readU8();

**Comment by sunnylqm** [comment]
合并到 https://github.com/reactnativecn/react-native-pushy/issues/161 跟踪
