### ISSUE TITLE
pushy bundle --platform ios

### ISSUE THREAD

**Issue by hulinhu521** [reactnativecn/react-native-pushy#186]
Bundling with React Native version:  0.53.0
Error: Cannot find module 'metro-bundler/src/babelRegisterOnly'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hulinhu/Desktop/react-naive/MyApp/node_modules/react-native-update/local-cli/lib/bundle.js:439:9)
    at Generator.next (<anonymous>)
    at step (/Users/hulinhu/Desktop/react-naive/MyApp/node_modules/react-native-update/local-cli/lib/bundle.js:310:191)
    at /Users/hulinhu/Desktop/react-naive/MyApp/node_modules/react-native-update/local-cli/lib/bundle.js:310:361
    at <anonymous>

**Comment by Geek-ch** [comment]
将\node_modules\react-native-update\local-cli\lib\bundle.js中439行的'metro-bundler/src/babelRegisterOnly'改为'metro-bundler/build/babelRegisterOnly'，原因是因为在metro-bundler引用的路径错了

**Comment by temple002** [comment]
在最新的版本中，路径又改了，把\node_modules\react-native-update\local-cli\lib\bundle.js中439行的'metro-bundler/src/babelRegisterOnly'改为'require('metro/src/babelRegisterOnly');'

**Comment by sunnylqm** [comment]
Fixed in https://github.com/reactnativecn/react-native-pushy/pull/205

**Comment by jingjingyang1006** [comment]
Error: Cannot find module 'metro/src/babelRegisterOnly'

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
 at Object.<anonymous> (/Users/project/AwesomeProject/node_modules/_react-native@0.55.4@react-native/setupBabel.js:10:27)

**Comment by sunnylqm** [comment]
@jingjingyang1006 不要使用cnpm

**Comment by sunnylqm** [comment]
@haipengz A pr is welcomed

**Comment by haipengz** [comment]
@sunnylqm PR submitted.

**Comment by zoukang1993** [comment]
将node_modules\react-native-update\local-cli\lib\bundle.js
的441行种的require('metro/src/babelRegisterOnly')改成require('metro-bundler/src/babelRegisterOnly')可成功运行。
