### ISSUE TITLE
真机debug的时候正常，一旦发布release.apk 在下载更新包结束后，系统就闪退

### ISSUE THREAD

**Issue by kiddysgu** [reactnativecn/react-native-pushy#208]
抓了一下错误
java.lang.RuntimeException: Error calling AppRegistry.runApplication
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:166)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:784)
Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
	... 7 more
com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:166)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:784)

提示是bundle打包不正确，请问这是怎么回事？

ps：去掉热更新的代码，一切正常
react-native-cli: 2.0.1
react-native: 0.55.4

另外https://bbs.reactnative.cn/和https://update.reactnative.cn/ 最近都打不开

**Comment by tdzl2003** [comment]
1. 这个错误通常也是uploadApk和本机运行的apk不是同一个apk导致的。
2. 去掉https的s，通过http访问。

**Comment by qmc2017** [comment]
我这有个一模一样的问题，花了我好几天还没有解决

**Comment by qingjiaowochengzd** [comment]
请问这个问题解决了吗？@qmc2017@tdzl2003@kiddysgu
