### ISSUE TITLE
pushy uploadIpa TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by solaronke** [reactnativecn/react-native-pushy#209]
pushy uploadIpa 时候出现这个错误：
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.exists (fs.js:235:3)
    at CertDownloader.pem (/Users/sophie/rnapps/ExpressProject/node_modules/cert-downloader/index.js:96:18)
    at CertDownloader.verify (/Users/sophie/rnapps/ExpressProject/node_modules/cert-downloader/index.js:131:11)
    at module.exports (/Users/sophie/rnapps/ExpressProject/node_modules/provisioning/index.js:7:10)
    at /Users/sophie/rnapps/ExpressProject/node_modules/ipa-metadata/node_modules/async/lib/async.js:731:23
    at /Users/sophie/rnapps/ExpressProject/node_modules/ipa-metadata/node_modules/async/lib/async.js:673:13
    at /Users/sophie/rnapps/ExpressProject/node_modules/ipa-metadata/node_modules/async/lib/async.js:230:13
    at _arrayEach (/Users/sophie/rnapps/ExpressProject/node_modules/ipa-metadata/node_modules/async/lib/async.js:81:9)
    at _each (/Users/sophie/rnapps/ExpressProject/node_modules/ipa-metadata/node_modules/async/lib/async.js:72:13)
试了好多次都还是这个错误，希望早点回复，谢谢

**Comment by huangzhifei** [comment]
@solaronke node版本太高导致的，降版本吧

**Comment by solaronke** [comment]
@huangzhifei 谢谢，我node10.2.1降到 6.11.3就可以了

**Comment by sunnylqm** [comment]
Fixed in https://github.com/reactnativecn/react-native-pushy/commit/818968aba7c021ceaf80d44c8bd01bf51aa71d3a
