### ISSUE TITLE
不兼容React Native 0.57.0-rc.3

### ISSUE THREAD

**Issue by thtTNT** [reactnativecn/react-native-pushy#223]
TypeError: Config.findOptional is not a function
    at Object.<anonymous> (/Users/thttnt/program/ReactNative/EmptyBox/node_modules/react-native-update/local-cli/lib/bundle.js:469:34)
    at Generator.next (<anonymous>)
    at step (/Users/thttnt/program/ReactNative/EmptyBox/node_modules/react-native-update/local-cli/lib/bundle.js:310:191)
    at /Users/thttnt/program/ReactNative/EmptyBox/node_modules/react-native-update/local-cli/lib/bundle.js:310:361
错误如下
环境 MacOS

**Comment by Jayxiang** [comment]
一样的错误   降低版本后  pushy bundle   会有.overrides is not allowed in preset options的错误

**Comment by sunnylqm** [comment]
试下刚发布的5.1.3版本

**Comment by sunnylqm** [comment]
应该在5.1.4中修复了  后续有问题请再开issue
