### ISSUE TITLE
pushy uploadApk failed

### ISSUE THREAD

**Issue by lymluck** [reactnativecn/react-native-pushy#238]
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 1. Received 2
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readUInt16LE (internal/buffer.js:134:5)
    at parseExtra (/Users/louis/rn/crm_app_xiugou/node_modules/adm-zip/zipEntry.js:151:25)
    at Object.set extra [as extra] (/Users/louis/rn/crm_app_xiugou/node_modules/adm-zip/zipEntry.js:206:13)
    at readEntries (/Users/louis/rn/crm_app_xiugou/node_modules/adm-zip/zipFile.js:40:17)
    at readMainHeader (/Users/louis/rn/crm_app_xiugou/node_modules/adm-zip/zipFile.js:72:3)
    at new module.exports (/Users/louis/rn/crm_app_xiugou/node_modules/adm-zip/zipFile.js:18:3)
    at new module.exports (/Users/louis/rn/crm_app_xiugou/node_modules/adm-zip/adm-zip.js:20:11)
    at new ApkReader (/Users/louis/rn/crm_app_xiugou/node_modules/node-apk-parser/lib/apkreader.js:23:20)
    at Function.ApkReader.readFile (/Users/louis/rn/crm_app_xiugou/node_modules/node-apk-parser/lib/apkreader.js:16:14)

**Comment by sunnylqm** [comment]
合并到 https://github.com/reactnativecn/react-native-pushy/issues/161 跟踪
