### ISSUE TITLE
更新之后切换报错，recreateReactContextInBackground should only be called after the initial createReactContextInBackground call.

### ISSUE THREAD

**Issue by ShellJor** [reactnativecn/react-native-pushy#242]
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at cn.reactnative.modules.update.UpdateModule$4.run(UpdateModule.java:142)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6699)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.AssertionError: recreateReactContextInBackground should only be called after the initial createReactContextInBackground call.
        at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
        at com.facebook.react.ReactInstanceManager.recreateReactContextInBackground(ReactInstanceManager.java:342)
        at java.lang.reflect.Method.invoke(Native Method) 
        at cn.reactnative.modules.update.UpdateModule$4.run(UpdateModule.java:142) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6699) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by ShellJor** [comment]
Help！！！！

**Comment by sunnylqm** [comment]
0.58应该暂时还不支持

**Comment by ShellJor** [comment]
我的是0.57.7 这个版本。

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有问题请重开issue
