### ISSUE TITLE
pushy bundle --platform android 报错

### ISSUE THREAD

**Issue by yohanceli** [reactnativecn/react-native-pushy#251]
```Bundling with React Native version:  0.58.6
Error: Cannot find module '/Users/username/Workspace/react-native/HP_VDPS_no_map/node_modules/@react-native-community/cli/build/tools/loadMetroConfig'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/username/Workspace/react-native/HP_VDPS_no_map/node_modules/react-native-update/local-cli/lib/bundle.js:473:20)
    at Generator.next (<anonymous>)
    at step (/Users/username/Workspace/react-native/HP_VDPS_no_map/node_modules/react-native-update/local-cli/lib/bundle.js:314:191)
    at /Users/username/Workspace/react-native/HP_VDPS_no_map/node_modules/react-native-update/local-cli/lib/bundle.js:314:361
```

react-native-update-cli: 0.1.0
react-native-update: 5.1.7
"react-native": "0.58.6"

**Comment by sunnylqm** [comment]
抱歉请更新到5.1.8
