### ISSUE TITLE
pushy publish --platform android 报错

### ISSUE THREAD

**Issue by yohanceli** [reactnativecn/react-native-pushy#252]
```
Uploading [===================                                                                          ] 16% 0.0s
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: upload.qiniu.com. is not in the cert's altnames: DNS:*.qbox.me, DNS:qbox.me
    at Object.checkServerIdentity (tls.js:228:17)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1059:27)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
```

无法上传至七牛

react-native-update-cli: 0.1.0
react-native-update: 5.1.8

**Comment by sunnylqm** [comment]
请重试

**Comment by yohanceli** [comment]
@sunnylqm 可以上传了，非常感谢
