### ISSUE TITLE
Android热更新完后，重新启动闪退

### ISSUE THREAD

**Issue by HanSonOne** [reactnativecn/react-native-pushy#254]
java.lang.RuntimeException: com.facebook.react.devsupport.JSException: SyntaxError: Unexpected end of script (/data/user/0/com.logisticspro/files/_update/Fp7IgA-0F2UoJCl4INr40Luhv0su/index.bundlejs:717)
        at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:24)
        at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:156)
        at com.facebook.react.cxxbridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:481)
        at com.facebook.react.cxxbridge.CatalystInstanceImpl.access$700(CatalystInstanceImpl.java:51)
        at com.facebook.react.cxxbridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:497)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:33)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
        at java.lang.Thread.run(Thread.java:764)

**Comment by sunnylqm** [comment]
请提供各种版本信息

**Comment by HanSonOne** [comment]
"react-native": "0.44.0",
"react-native-update": "^4.0.6",
node v11.12.0
compileSdkVersion 28
buildToolsVersion '28.0.3'

**Comment by sunnylqm** [comment]
抱歉5.x以下版本我们不再提供支持了

**Comment by HanSonOne** [comment]
"react-native": "0.46.4",
"react-native-cli": "2.0.1",
"react-native-update": "^5.1.8",
热更新还是不能正常更新
checkUpdate方法抛异常提示报错TypeError：Network request failed

**Comment by HanSonOne** [comment]
使用提示更新，重新启动报错
2019-04-23 14:25:10.140 12444-12497/com.logisticspro E/ReactNativeJNI: Got JS Exception: ReferenceError: Can't find variable: requi (/data/user/0/com.logisticspro/files/_update/FkPdNO8GufHg-FXAJKIT7oucVPbx/index.bundlejs:619)
2019-04-23 14:25:10.140 12444-12497/com.logisticspro E/ReactNativeJNI: Got JS Stack: global code@/data/user/0/com.logisticspro/files/_update/FkPdNO8GufHg-FXAJKIT7oucVPbx/index.bundlejs:619:7
    
    --------- beginning of crash
2019-04-23 14:25:10.141 12444-12497/com.logisticspro E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: com.logisticspro, PID: 12444
    java.lang.RuntimeException: com.facebook.react.devsupport.JSException: ReferenceError: Can't find variable: requi (/data/user/0/com.logisticspro/files/_update/FkPdNO8GufHg-FXAJKIT7oucVPbx/index.bundlejs:619)
        at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:24)
        at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:156)
        at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:473)
        at com.facebook.react.bridge.CatalystInstanceImpl.access$700(CatalystInstanceImpl.java:41)
        at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:489)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:33)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.facebook.react.devsupport.JSException: ReferenceError: Can't find variable: requi (/data/user/0/com.logisticspro/files/_update/FkPdNO8GufHg-FXAJKIT7oucVPbx/index.bundlejs:619)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:193) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: com.facebook.jni.CppException: ReferenceError: Can't find variable: requi (/data/user/0/com.logisticspro/files/_update/FkPdNO8GufHg-FXAJKIT7oucVPbx/index.bundlejs:619)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
        at android.os.Looper.loop(Looper.java:193) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by sunnylqm** [comment]
有报错
`Can't find variable: requi `

**Comment by ydbwwhq** [comment]
java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {d66328d} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
        at android.os.Handler.enqueueMessage(Handler.java:662)
        at android.os.Handler.sendMessageAtTime(Handler.java:631)
        at android.os.Handler.sendMessageDelayed(Handler.java:601)
        at android.os.Handler.post(Handler.java:357)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:70)
        at com.facebook.react.bridge.ReactContext.runOnJSQueueThread(ReactContext.java:306)
        at com.facebook.react.uimanager.events.EventDispatcher$ScheduleDispatchFrameCallback.doFrame(EventDispatcher.java:302)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:778)
        at android.view.Choreographer.doFrame(Choreographer.java:710)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6602)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:453)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)


使用 "react-native-update": "^5.2.1"版本，安卓热更新以后重启闪退

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有闪退问题请重开issue
