### ISSUE TITLE
"react-native-update": "^5.2.2", 热更新后闪退

### ISSUE THREAD

**Issue by iaminvictus1993** [reactnativecn/react-native-pushy#271]
"react-native-update": "^5.2.2",
"react-native": "0.59.9",

**Comment by vae13** [comment]
我也出现了这个问题

**Comment by sunnylqm** [comment]
请给出报错的日志

**Comment by kimyyx** [comment]
我build到正式包的时候，热更新闪退
"react-native": "0.59.5",
"react-native-update": "^5.2.3",

错误信息是：
**Activity has leaked window that was originally added**

**Comment by sunnylqm** [comment]
需要更完整的日志

**Comment by Halkingxp** [comment]
我也是闪退
    "react-native": "0.60.5",
    "react-native-update": "^5.2.3",
//////////////////
info信息：
![image](https://user-images.githubusercontent.com/50072824/63836634-78d08480-c9ac-11e9-940f-c591efc1840d.png)

闪退信息，提示找不到bundlejs文件
    Process: com.hotupdate5, PID: 9225
    com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/com.hotupdate5/files/_update/{hash隐藏}/index.bundlejs: No such file or directory
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:226)
        at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:52)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:249)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1155)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:124)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:948)

**Comment by Halkingxp** [comment]
@sunnylqm 麻烦看看

**Comment by sunnylqm** [comment]
收到，在分析

**Comment by sunnylqm** [comment]
确定手机存储空间足够吗？

**Comment by sunnylqm** [comment]
请尝试5.2.5版本，在bundle命令后请注意生成的ppk文件大小是否正常（不应该只有几k）
