### ISSUE TITLE
android 正式版报错

### ISSUE THREAD

**Issue by gyfgyf** [reactnativecn/react-native-pushy#274]
在集成react-native-pushy后，使用react-native-pushy 官方例子代码中，测试环境还算正常，在正式发布环境，点击‘点击这里检查更新’报错，导致应用闪退，在开启debug 后显示了错误
![WechatIMG1](https://user-images.githubusercontent.com/25699680/63908608-5ee97d00-ca52-11e9-93cd-02076b6d75ae.jpeg)

环境为：
"react": "16.8.6",
 "react-native": "0.60.4",
"react-native-update": "^5.2.3",

**Comment by sunnylqm** [comment]
截图是什么环境？哪里的代码调用了console.assert?

**Comment by gyfgyf** [comment]
release版的，在点击检查更新按钮时导致app 闪退，所以我在bundle.gradle 文件中打开了debug
buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
             debuggable true
      
        }
    }

**Comment by sunnylqm** [comment]
热更新必须是同一份apk，不能重新编译
闪退报错可以看adb logcat

**Comment by gyfgyf** [comment]
我不是很理解什么是同一份apk,我是每次执行pushy 前，更改版本号，然后执行./gradlew bundleRelease，最后执行pushy uploadApk android/app/build/outputs/apk/release/app-release.apk

**Comment by sunnylqm** [comment]
热更新的意思就是只更新js资源啊（bundle），如果每次都重新上传apk那为什么要用热更新？

**Comment by gyfgyf** [comment]
我现在即使打包版本是versionName "1.0.33"，release 的app 显示也是1.0.33，点击依然是闪退，报错上面的错误，而在debug 模式会提示当前为最新版本

**Comment by sunnylqm** [comment]
闪退报错请贴adb logcat，以及你确定你的新的bundle是在1.0.33的基础上改的吗

**Comment by gyfgyf** [comment]
你可能没理解我，我现在发布时的是1.0.33，我什么也不做，是不是应该显示已经是最新版本？
adb logcat BufferQueueProducer: [] mConsumerName == NULL!!!!!!

**Comment by sunnylqm** [comment]
原生版本和js版本并没有关系

**Comment by gyfgyf** [comment]
我现在打包的是1.0.33，我上传到pushy 的也是1.0.33， 测试环境点击检查更新，显示已经是最新版，打包apk 点击检查跟新，直接闪退，现在跟刷新有什么关系？，我的期待是打包好的apk 像测试版的一样提示我已经是最新版，而不是闪退，

**Comment by sunnylqm** [comment]
我不太明白你的测试环境或者什么环境的区别是什么，要保证的是：你`上传到pushy的那个apk`应该跟你`正在使用热更新的设备上的apk`一致
此外，`闪退报错请贴adb logcat`

**Comment by gyfgyf** [comment]
测试环境就是连接数据线的或者真机调试的，发布就是正常使用的可以做推广的apk
![CAABB69C-BA8A-408A-97B4-2EDF4B38F8C6](https://user-images.githubusercontent.com/25699680/63924115-4b520c80-ca7a-11e9-8f23-45db4e994bf0.png)
![BCB8B54A-D1C8-46FF-AF6E-8B3C5AE567E0](https://user-images.githubusercontent.com/25699680/63924125-4d1bd000-ca7a-11e9-87c1-530896f98ad8.png)
![6D7D2E55-0A6F-45B9-92C5-B9B9538B649D](https://user-images.githubusercontent.com/25699680/63924130-4e4cfd00-ca7a-11e9-862b-d59adaada573.png)
![14EC8982-18D4-40D1-9A6E-D88A241D9D98](https://user-images.githubusercontent.com/25699680/63924136-5016c080-ca7a-11e9-8ff2-4ee7f7a16d76.png)
![WechatIMG2](https://user-images.githubusercontent.com/25699680/63924141-5311b100-ca7a-11e9-9fe5-3be4d7df8fa6.jpeg)

**Comment by sunnylqm** [comment]
重点不在于环境，在于是否同一份apk（严格来说，哪怕代码不动，重新编译一次都不算）
以及再重复一次：闪退报错请贴adb logcat

**Comment by gyfgyf** [comment]
![WeChat668fba2e230fef9454af2c9451ebf542](https://user-images.githubusercontent.com/25699680/63928637-7c363f80-ca82-11e9-89f8-246bf9cff969.png)
2019-08-29 17:24:43.308 4658-4745/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.taotao, PID: 4658
    com.facebook.react.common.JavascriptException: console.assert is not a function. (In 'console.assert(null!=o,"'this' is expected an Event object, but got",n)', 'console.assert' is undefined), stack:
    o@112:173
    w@112:1841
    dispatchEvent@112:5597
    value@111:6130
    value@111:2835
    value@44:1280
    value@23:3518
    <unknown>@23:822
    value@23:2772
    value@23:794
    value@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:165)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:760)
2019-08-29 17:24:43.330 4658-4799/? E/libc: Access denied finding property "persist.radio.meid"
2019-08-29 17:24:43.330 4658-4799/? E/libc: Access denied finding property "ro.ril.oem.meid"
2019-08-29 17:24:43.351 4658-4799/? E/libc: Access denied finding property "ro.ril.miui.imei0"
2019-08-29 17:24:43.352 4658-4799/? E/libc: Access denied finding property "ro.ril.miui.imei"
2019-08-29 17:24:43.352 4658-4799/? E/libc: Access denied finding property "ro.ril.miui.imei1"
2019-08-29 17:24:43.352 4658-4799/? E/libc: Access denied finding property "ro.ril.oem.imei1"
2019-08-29 17:24:43.352 4658-4799/? E/libc: Access denied finding property "ro.ril.oem.imei2"
2019-08-29 17:24:43.353 4658-4799/? E/libc: Access denied finding property "persist.radio.imei1"
2019-08-29 17:24:43.353 4658-4799/? E/libc: Access denied finding property "persist.radio.imei2"
2019-08-29 17:24:43.631 1659-1777/? E/InputDispatcher: channel 'b757a15 com.taotao/com.taotao.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-08-29 17:24:43.633 1659-1801/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=713, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
2019-08-29 17:24:43.640 474-2674/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2019-08-29 17:24:43.660 2108-2108/? E/Launcher.RecommendLog: don't request, because recommend screen can't show
2019-08-29 17:24:43.660 2108-2108/? E/Launcher.RecommendLog: folder display and try to request recommend list
2019-08-29 17:24:43.660 2108-2108/? E/Launcher.RecommendLog: don't request, because recommend screen can't show
2019-08-29 17:24:43.660 2108-2108/? E/Launcher.RecommendLog: folder display and try to request recommend list
2019-08-29 17:24:43.660 2108-2108/? E/Launcher.RecommendLog: don't request, because recommend screen can't show
2019-08-29 17:24:43.660 2108-2108/? E/Launcher.RecommendLog: folder display and try to request recommend list
2019-08-29 17:24:59.186 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
2019-08-29 17:25:12.218 1659-1836/? E/AppScanObserverService: Result available, null observers for user: 0
2019-08-29 17:25:13.769 3801-3801/? E/QZLog: exitProcess call,destroy()
2019-08-29 17:25:14.426 751-751/? E/cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
    : 00:00:00:00:00:00
2019-08-29 17:25:14.426 751-751/? E/cnss-daemon: Invalid mac address: 0x555555f110M
2019-08-29 17:25:25.166 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
2019-08-29 17:25:42.236 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 16
2019-08-29 17:25:50.737 751-751/? E/cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
    : 00:00:00:00:00:00
2019-08-29 17:25:50.737 751-751/? E/cnss-daemon: Invalid mac address: 0x555555f110M
2019-08-29 17:25:57.766 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
2019-08-29 17:26:03.906 751-751/? E/cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
    : 00:00:00:00:00:00
2019-08-29 17:26:03.906 751-751/? E/cnss-daemon: Invalid mac address: 0x555555f110M
2019-08-29 17:26:17.046 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
2019-08-29 17:26:33.076 751-751/? E/cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
    : 00:00:00:00:00:00
2019-08-29 17:26:33.077 751-751/? E/cnss-daemon: Invalid mac address: 0x555555f110M
2019-08-29 17:27:15.966 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
2019-08-29 17:27:23.026 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 16
2019-08-29 17:27:23.040 751-751/? E/cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
    : 00:00:00:00:00:00
2019-08-29 17:27:23.040 751-751/? E/cnss-daemon: Invalid mac address: 0x555555f110M
2019-08-29 17:27:35.332 1932-2241/? E/SQLiteLog: (1) no such table: mr_friend_115C343463041F8763D7552FDCE43C9F_New
2019-08-29 17:27:52.238 1659-1836/? E/AppScanObserverService: Result available, null observers for user: 0
2019-08-29 17:27:52.584 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
2019-08-29 17:27:53.366 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
2019-08-29 17:28:04.975 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
2019-08-29 17:28:21.076 751-751/? E/cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
    : 00:00:00:00:00:00
2019-08-29 17:28:21.076 751-751/? E/cnss-daemon: Invalid mac address: 0x555555f110M
2019-08-29 17:28:21.831 4590-4911/? E/WakePathManager: doUpdate(user 10): insertResponseToDb failed!!
2019-08-29 17:28:40.006 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
2019-08-29 17:28:45.057 751-751/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 16
2019-08-29 17:28:45.073 751-751/? E/cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
    : 00:00:00:00:00:00
2019-08-29 17:28:45.073 751-751/? E/cnss-daemon: Invalid mac address: 0x555555f110M

**Comment by gyfgyf** [comment]
![WeChat668fba2e230fef9454af2c9451ebf542](https://user-images.githubusercontent.com/25699680/63928682-91ab6980-ca82-11e9-8ae1-3dc01231787f.png)

**Comment by sunnylqm** [comment]
感觉是代码上的问题，哪里用到了console.assert这个在rn环境中并不存在的方法

**Comment by sunnylqm** [comment]
非release模式下应该能看到具体报错的文件和位置

**Comment by gyfgyf** [comment]
非release 版 不报错，

**Comment by gyfgyf** [comment]
import React, { Component } from "react";

import {
  AppRegistry,
  StyleSheet,
  Platform,
  Text,
  View,
  Alert,
  TouchableOpacity,
  Linking
} from "react-native";

import {
  isFirstTime,
  isRolledBack,
  packageVersion,
  currentVersion,
  checkUpdate,
  downloadUpdate,
  switchVersion,
  switchVersionLater,
  markSuccess
} from "react-native-update";

import _updateConfig from "../../../update.json";
const { appKey } = _updateConfig[Platform.OS];

export default class MyProject extends Component {
  componentWillMount() {
    if (isFirstTime) {
      Alert.alert(
        "提示",
        "这是当前版本第一次启动,是否要模拟启动失败?失败将回滚到上一版本",
        [
          {
            text: "是",
            onPress: () => {
              throw new Error("模拟启动失败,请重启应用");
            }
          },
          {
            text: "否",
            onPress: () => {
              markSuccess();
            }
          }
        ]
      );
    } else if (isRolledBack) {
      Alert.alert("提示", "刚刚更新失败了,版本被回滚.");
    }
  }
  doUpdate = info => {
    downloadUpdate(info)
      .then(hash => {
        Alert.alert("提示", "下载完毕,是否重启应用?", [
          {
            text: "是",
            onPress: () => {
              switchVersion(hash);
            }
          },
          { text: "否" },
          {
            text: "下次启动时",
            onPress: () => {
              switchVersionLater(hash);
            }
          }
        ]);
      })
      .catch(err => {
        Alert.alert("提示", "更新失败.");
      });
  };
  checkUpdate = () => {
    checkUpdate(appKey)
      .then(info => {
        if (info.expired) {
          Alert.alert("提示", "您的应用版本已更新,请前往应用商店下载新的版本", [
            {
              text: "确定",
              onPress: () => {
                info.downloadUrl && Linking.openURL(info.downloadUrl);
              }
            }
          ]);
        } else if (info.upToDate) {
          Alert.alert("提示", "您的应用版本已是最新.");
        } else {
          Alert.alert(
            "提示",
            "检查到新的版本" + info.name + ",是否下载?\n" + info.description,
            [
              {
                text: "是",
                onPress: () => {
                  this.doUpdate(info);
                }
              },
              { text: "否" }
            ]
          );
        }
      })
      .catch(err => {
        Alert.alert("提示", "更新失败.");
      });
  };
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>欢迎使用热更新服务</Text>
        <Text style={styles.instructions}>
          这是版本一 {"\n"}
          当前包版本号: {packageVersion}
          {"\n"}
          当前版本Hash: {currentVersion || "(空)"}
          {"\n"}
        </Text>
        <TouchableOpacity onPress={this.checkUpdate}>
          <Text style={styles.instructions}>
            点击这里检查更新65432112345612122222
          </Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5
  }
});



此代码完全拷贝react-native-pushy 官方示例

**Comment by gyfgyf** [comment]
apk 崩溃也只只在点击检查更新下的情况，

**Comment by sunnylqm** [comment]
方便给个repo地址我看下吗

**Comment by gyfgyf** [comment]
你好，这个问题的原因已经找到了，原因是是我在！__dev__ 的情况下禁用了console的问题，但是我又面临新的问题，relsase 环境下，点击刷新能够正常提示，并提示下载，但app 不会重启，重启之后报错，说找不到文件

**Comment by sunnylqm** [comment]
最近有几个这样的报错，但我还没办法重现

**Comment by gyfgyf** [comment]
我发现失败的情况下，都显示不出来hash 值

**Comment by sunnylqm** [comment]
试下5.2.8版本，应该解决了重启的问题
