### ISSUE TITLE
android release 更新失败

### ISSUE THREAD

**Issue by gyfgyf** [reactnativecn/react-native-pushy#275]
"react": "16.8.6",
 "react-native": "0.60.4",
"react-native-update": "^5.2.3",

报错显示
点击检查更新，提示下载成功，是否重启app,确认重启报错，logcat 报错显示，

2019-08-31 00:14:09.315 9470-9470/com.taotao E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.taotao, PID: 9470
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.taotao/com.taotao.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.Screen$ScreenFragment: calling Fragment constructor caused an exception
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4626)
        at android.app.ActivityThread.-wrap19(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
     Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.Screen$ScreenFragment: calling Fragment constructor caused an exception
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:465)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:50)
        at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:80)
        at androidx.fragment.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:3109)
        at androidx.fragment.app.FragmentController.restoreAllState(FragmentController.java:158)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:344)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:51)
        at com.taotao.MainActivity.onCreate(MainActivity.java:24)
        at android.app.Activity.performCreate(Activity.java:6845)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4626) 
        at android.app.ActivityThread.-wrap19(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6375) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:443)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:50) 
        at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:80) 
        at androidx.fragment.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:3109) 
        at androidx.fragment.app.FragmentController.restoreAllState(FragmentController.java:158) 
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:344) 
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:51) 
        at com.taotao.MainActivity.onCreate(MainActivity.java:24) 
        at android.app.Activity.performCreate(Activity.java:6845) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4626) 
        at android.app.ActivityThread.-wrap19(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6375) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802) 
     Caused by: java.lang.IllegalStateException: Screen fragments should never be restored
        at com.swmansion.rnscreens.Screen$ScreenFragment.<init>(Screen.java:24)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:443) 
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:50) 
        at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:80) 
        at androidx.fragment.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:3109) 
        at androidx.fragment.app.FragmentController.restoreAllState(FragmentController.java:158) 
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:344) 
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:51) 
        at com.taotao.MainActivity.onCreate(MainActivity.java:24) 
        at android.app.Activity.performCreate(Activity.java:6845) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4626) 
        at android.app.ActivityThread.-wrap19(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6375) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802) 
2019-08-31 00:14:09.331 9470-9746/com.taotao E/libc: Access denied finding property "persist.radio.meid"
2019-08-31 00:14:09.331 9470-9746/com.taotao E/libc: Access denied finding property "ro.ril.oem.meid"
2019-08-31 00:14:09.347 9470-9746/com.taotao E/libc: Access denied finding property "ro.ril.miui.imei0"
2019-08-31 00:14:09.347 9470-9746/com.taotao E/libc: Access denied finding property "ro.ril.miui.imei"
2019-08-31 00:14:09.348 9470-9746/com.taotao E/libc: Access denied finding property "ro.ril.miui.imei1"
2019-08-31 00:14:09.348 9470-9746/com.taotao E/libc: Access denied finding property "ro.ril.oem.imei1"
2019-08-31 00:14:09.348 9470-9746/com.taotao E/libc: Access denied finding property "ro.ril.oem.imei2"
2019-08-31 00:14:09.349 9470-9746/com.taotao E/libc: Access denied finding property "persist.radio.imei1"
2019-08-31 00:14:09.350 9470-9746/com.taotao E/libc: Access denied finding property "persist.radio.imei2"
![image](https://user-images.githubusercontent.com/25699680/64035862-63ae4e00-cb84-11e9-9f73-b3ae67b9e219.png)

**Comment by sunnylqm** [comment]
好像是用到了react-native-screens? 先去掉那个试试吧

**Comment by gyfgyf** [comment]
我注释掉了
// import { useScreens } from 'react-native-screens';
// useScreens();
结果依然报错，
请问是卸载掉react-native-screen 吗

**Comment by sunnylqm** [comment]
试下这里提到的方案  https://github.com/kmagiera/react-native-screens/issues/17#issuecomment-424704067

**Comment by sunnylqm** [comment]
请尝试上面链接提到的方案以及最新版本，如还有问题请重开issue
