### ISSUE TITLE
Android调用switchVersion或switchVersionLater重启后崩溃

### ISSUE THREAD

**Issue by zd1471278687** [reactnativecn/react-native-pushy#290]
![WechatIMG2](https://user-images.githubusercontent.com/9609825/67664350-6f5e9b00-f9a2-11e9-9271-5e4f8b560ea1.jpeg)
报错信息如图
环境：
使用版本5.2.8
react-native版本0.59.9

**Comment by sunnylqm** [comment]
只能在release版本中测试热更新

**Comment by zd1471278687** [comment]
> 只能在release版本中测试热更新

release版本也会崩溃，这是在debug版本中抓到的报错信息

**Comment by sunnylqm** [comment]
debug版本的报错没有参考意义，请给出release版本的logcat报错



---原始邮件---
发件人: "davidzhang"<notifications@github.com&gt;
发送时间: 2019年10月29日(星期二) 上午9:40
收件人: "reactnativecn/react-native-pushy"<react-native-pushy@noreply.github.com&gt;;
抄送: "Sunny Luo"<sunnylqm@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [reactnativecn/react-native-pushy] Android调用switchVersion或switchVersionLater重启后崩溃 (#290)


 
只能在release版本中测试热更新
  
release版本也会崩溃，这是在debug版本中抓到的报错信息

**Comment by zd1471278687** [comment]
2019-10-29 13:45:04.518 12282-12317/? E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    com.facebook.jni.CppException: getPropertyAsObject: property '__fbRequireBatchedBridge' is not an Object
    
    no stack
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)

**Comment by zd1471278687** [comment]
> debug版本的报错没有参考意义，请给出release版本的logcat报错
> […](#)
> ---原始邮件--- 发件人: "davidzhang"<notifications@github.com&gt; 发送时间: 2019年10月29日(星期二) 上午9:40 收件人: "reactnativecn/react-native-pushy"<react-native-pushy@noreply.github.com&gt;; 抄送: "Sunny Luo"<sunnylqm@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [reactnativecn/react-native-pushy] Android调用switchVersion或switchVersionLater重启后崩溃 (#290) 只能在release版本中测试热更新 release版本也会崩溃，这是在debug版本中抓到的报错信息 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

2019-10-29 13:45:04.518 12282-12317/? E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    com.facebook.jni.CppException: getPropertyAsObject: property '__fbRequireBatchedBridge' is not an Object
    
    no stack
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)

**Comment by sunnylqm** [comment]
看官方issue可能跟升级后的缓存有关，清掉缓存重新打包试试
https://github.com/facebook/react-native/issues/25455#issuecomment-507673042
