### ISSUE TITLE
旧版本RN0.38.1  不能热更新，先提示更新react-native-update-cli，更新后还是不行

### ISSUE THREAD

**Issue by macxie** [reactnativecn/react-native-pushy#335]
旧版本RN0.38.1  不能热更新，先提示更新react-native-update-cli，更新后还是不行

pushy bundle --platform android
Bundling with React Native version:  0.38.1
[2020-4-29 10:37:00 AM] <START> Initializing Packager
[2020-4-29 10:37:00 AM] <START> Building in-memory fs for JavaScript
[2020-4-29 10:37:00 AM] <END>   Building in-memory fs for JavaScript (86ms)
[2020-4-29 10:37:00 AM] <START> Building Haste Map
[2020-4-29 10:37:01 AM] <END>   Building Haste Map (472ms)
[2020-4-29 10:37:01 AM] <END>   Initializing Packager (634ms)
[2020-4-29 10:37:01 AM] <START> Transforming files
[2020-4-29 10:37:23 AM] <END>   Transforming files (21965ms)
bundle: start
bundle: finish
bundle: Writing bundle output to: /Users/develop03/Documents/RNProjects/tj_app/build/intermedia/android/index.bundlejs
bundle: Copying 36 asset files
bundle: Done writing bundle output
bundle: Done copying assets
Packing
Bundled saved to: build/output/android.1588127818585.ppk
Would you like to publish it?(Y/N) y
Error: 请升级cli后再尝试( npm i -g react-native-update-cli )
    at /Users/develop03/Documents/RNProjects/tj_app/node_modules/react-native-update/local-cli/lib/api.js:8:27
    at Generator.next (<anonymous>)
    at step (/Users/develop03/Documents/RNProjects/tj_app/node_modules/react-native-update/local-cli/lib/api.js:82:191)
    at /Users/develop03/Documents/RNProjects/tj_app/node_modules/react-native-update/local-cli/lib/api.js:82:361
    at process._tickCallback (internal/process/next_tick.js:68:7)

按提示更新后，进行操作热更新提示index.js不存在：

pushy bundle --platform android
Bundling with react-native:  0.38.1
react-native-update-cli: 1.1.4
react-native-update: 4.0.6
react-native : 0.38.1

Running bundle command: node node_modules/react-native/local-cli/cli.js bundle --assets-dest build/intermedia/android --bundle-output build/intermedia/android/index.bundlejs --dev false --entry-file index.js --platform android --reset-cache
[2020-4-29 11:21:29 AM] <START> Initializing Packager
[2020-4-29 11:21:29 AM] <START> Building in-memory fs for JavaScript
[2020-4-29 11:21:30 AM] <END>   Building in-memory fs for JavaScript (69ms)
[2020-4-29 11:21:30 AM] <START> Building Haste Map
[2020-4-29 11:21:30 AM] <END>   Building Haste Map (323ms)
[2020-4-29 11:21:30 AM] <END>   Initializing Packager (456ms)
[2020-4-29 11:21:30 AM] <START> Transforming files

Cannot find entry file index.js in any of the roots: 
Error: "react-native bundle" command exited with code 1.
    at ChildProcess.reactNativeBundleProcess.on (/usr/local/lib/node_modules/react-native-update-cli/lib/bundle.js:90:16)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)

请问我要更新什么版本才能将 rn 0.38.1，热更新生成差异包。谢谢

**Comment by sunnylqm** [comment]
可以指定entryFile参数
https://github.com/reactnativecn/react-native-pushy/blob/46c7aa88dd4b8cc82342324dd48cb7b7299d31d3/docs/cli.md#pushy-bundle
```
pushy bundle --entryFile index.android.js
```

**Comment by macxie** [comment]
@sunnylqm  好的谢谢，我们将升级提到最新日程中
