### ISSUE TITLE
Bundling with React Native version:  0.33.0

### ISSUE THREAD

**Issue by lijinchao2007** [reactnativecn/react-native-pushy#34]
Bundling with React Native version:  0.33.0
AssertionError: missing path
    at Module.require (module.js:481:3)
    at require (internal/module.js:20:19)
    at Object.get (/Users/joshua/dn/dn_react/node_modules/react-native/local-cli/util/Config.js:39:20)
    at Object.<anonymous> (/Users/joshua/dn/dn_react/node_modules/react-native-update/local-cli/lib/bundle.js:430:36)
    at undefined.next (native)
    at step (/Users/joshua/dn/dn_react/node_modules/react-native-update/local-cli/lib/bundle.js:44:191)
    at /Users/joshua/dn/dn_react/node_modules/react-native-update/local-cli/lib/bundle.js:44:368

**Comment by tdzl2003** [comment]
fixed in 3.0.2
