### ISSUE TITLE
cli-1.1.7无法更新

### ISSUE THREAD

**Issue by grh1236** [reactnativecn/react-native-pushy#343]
只要输入pushy就会报错
`/usr/local/lib/node_modules/react-native-update-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-update-cli/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
`

**Comment by sunnylqm** [comment]
node版本多少？应该需要10以上

**Comment by sunnylqm** [comment]
刚更新了个cli版本，去掉了fs-extra依赖，也可以升级cli试试
