### ISSUE TITLE
pushy uploadApk android ...apk执行几次？

### ISSUE THREAD

**Issue by jinghun1999** [reactnativecn/react-native-pushy#37]
我已经执行过了，在web上也出现了版本1.0了。我下次修改代码生成了新的release.apk文件放到服务器上，还需要执行puloadApk吗？
第二次执行出现了错误了。

```
Error: Validation error
    at D:\Work\GitHub\Tuorui\node_modules\react-native-update\local-cli\lib\api.js:77:27
    at next (native)
    at step (D:\Work\GitHub\Tuorui\node_modules\react-native-update\local-cli\lib\api.js:19:191)
    at D:\Work\GitHub\Tuorui\node_modules\react-native-update\local-cli\lib\api.js:19:368
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by jinghun1999** [comment]
显示文件上传了100%了。但最后面出现了如上错误。

**Comment by sunnylqm** [comment]
热更新的目的就是更新js文件，所以
1、不要动原生文件，不要再次生成apk，只使用pushy bundle命令生成新的jsbundle文件  
2、如果改了原生文件，或者重新生成了apk，那么我们认为是新的原生版本，请重新uploadapk作为新的热更新起点

**Comment by jinghun1999** [comment]
按你第二条说的，重新执行uploadapk报错了，如下：
如果发布多个包？用什么命令？

```
pushy uploadApk android/app/build/outputs/apk/app-release.apk
Uploading [==========================================================] 100% 0.0s
Validation error
```

回复

**Comment by tdzl2003** [comment]
如果发布多个包，每个包的版本号(VersionCode, VersionName)必须不一样，上面这个错误是说你上传了一个相同版本号的包。

**Comment by forrest23** [comment]
@tdzl2003 我想发布多个包，然后我修改了VersionCode, VersionName，然后上传之后，还是报Validation error，应该是服务端判断有bug了

**Comment by jewdore** [comment]
先删除以前的
