### ISSUE TITLE
华为荣耀 点击热更新闪退

### ISSUE THREAD

**Issue by xuyazhong** [reactnativecn/react-native-pushy#370]
react-native-cli: 2.0.1
react-native: 0.58.6
react-native-update-cli: 1.1.11
react-native-update: 5.3.0

点击否可以正常使用，点击是直接闪退

com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/com.myApp/files/_update/FgO0OWDZduNZDK8SmzWXFvv0jvB1/index.bundlejs: No such file or directory
	at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
	at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:231)
	at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:53)
	at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:253)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1152)
	at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
	at java.lang.Thread.run(Thread.java:784)

**Comment by sunnylqm** [comment]
可否升级react-native-update到最新版本后再试试？
