### ISSUE TITLE
执行pushy 的相关命令，报错Server error

### ISSUE THREAD

**Issue by weber-cd** [reactnativecn/react-native-pushy#449]
```cmd
pushy selectApp --platform ios
Error: Server error: [object Object]
    at query (/Users/weber/.nvm/versions/node/v18.19.1/lib/node_modules/react-native-update-cli/lib/api.js:106:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async listApp (/Users/weber/.nvm/versions/node/v18.19.1/lib/node_modules/react-native-update-cli/lib/app.js:52:20)
    at async chooseApp (/Users/weber/.nvm/versions/node/v18.19.1/lib/node_modules/react-native-update-cli/lib/app.js:72:16)
    at async Object.selectApp (/Users/weber/.nvm/versions/node/v18.19.1/lib/node_modules/react-native-update-cli/lib/app.js:110:47)
```

**Comment by weber-cd** [comment]
经过排查，定位发现是未登录的原因。希望可以完善这个报错信息[object Object]

**Comment by sunnylqm** [comment]
感谢反馈，已更新cli
