### ISSUE TITLE
热更新上传APK报错

### ISSUE THREAD

**Issue by Forget451** [reactnativecn/react-native-pushy#84]
Error: Validation error
    at D:\YunFile\node_modules\react-native-update\local-cli\lib\api.js:77:27
    at next (native)
    at step (D:\YunFile\node_modules\react-native-update\local-cli\lib\api.js:19:191)
    at D:\YunFile\node_modules\react-native-update\local-cli\lib\api.js:19:368
    at process._tickCallback (internal/process/next_tick.js:103:7)

在用pushy uploadApk android/app/build/outputs/apk/app-release.apk上传APK时会报以上错误信息，请教大神如何解决？

**Comment by sunnylqm** [comment]
需要修改build.gradle里的版本号后再上传

**Comment by xqwIOS** [comment]
请问是修改versionCode 的版本号吗？
